server:
    port: 8888
spring:
    application:
        name: configserver
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/venuguntupalli/scf-config-repository.git
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka